apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-service
  name: echo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-service
    spec:
      containers:
      - name: echo-service
        image: echo-service
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service-api
spec:
  selector:
    app: echo-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
